### ISSUE TITLE
Example project not compiling

### ISSUE THREAD

**Issue by MarcSky** [onmyway133/RoughSwift#1]
Hello. I tried to compiling example project but I facing with problem. Example project not compiling. I getting next mistake:

```
Showing Recent Messages
:-1: .../Example/RoughSwiftDemo/Pods/Pods/Target Support Files/Pods-RoughSwiftDemo/Pods-RoughSwiftDemo.debug.xcconfig: unable to open file (in target "RoughSwiftDemo" in project "RoughSwiftDemo") (in target 'RoughSwiftDemo')

```
How to resolve this problem?

And we can't to install this project with command 
`pod 'RoughSwift'
`
We getting next mistake
`[!] Unable to find a specification for `RoughSwift``
thank you for help and great project

**Comment by onmyway133** [comment]
@MarcSky Hi, can you run `pod repo update` to update the CocoaPods master specs repo?
